In [1]:
import pandas as pd
import numpy as np
from openpyxl import load_workbook

In [2]:
df_144 = pd.read_excel('data/81-144.xlsx')
df_145 = pd.read_excel('data/81-145.xlsx')
df_146 = pd.read_excel('data/81-146.xlsx')
df_147 = pd.read_excel('data/81-147.xlsx')
df_151 = pd.read_excel('data/81-151.xlsx')
df_152 = pd.read_excel('data/81-152.xlsx')
df_153 = pd.read_excel('data/81-153.xlsx')
df_154 = pd.read_excel('data/81-154.xlsx')
df_155 = pd.read_excel('data/81-155.xlsx')
df_156 = pd.read_excel('data/81-156.xlsx')
df_157 = pd.read_excel('data/81-157.xlsx')
df_158 = pd.read_excel('data/81-158.xlsx')
df_163 = pd.read_excel('data/81-163.xlsx')
df_164 = pd.read_excel('data/81-164.xlsx')
df_167 = pd.read_excel('data/81-167.xlsx')
df_168 = pd.read_excel('data/81-168.xlsx')
df_169 = pd.read_excel('data/81-169.xlsx')
df_170 = pd.read_excel('data/81-170.xlsx')
df_172 = pd.read_excel('data/81-172.xlsx')
df_173 = pd.read_excel('data/81-173.xlsx')
df_174 = pd.read_excel('data/81-174.xlsx')
df_175 = pd.read_excel('data/81-175.xlsx')
df_177 = pd.read_excel('data/81-177.xlsx')
df_186 = pd.read_excel('data/81-186.xlsx')
df_188 = pd.read_excel('data/81-188.xlsx')
df_197 = pd.read_excel('data/81-197.xlsx')

In [3]:
df_144.head(3)

,Linera density,SA linear,Density yarn,Strength Gpa,Module Gpa,lengthening,Mass size,breaking the loop,Surface density of the fabric,Prepreg surface density,...,viscosity,Gelation time,Resin Tg,technology,Thickness of the monolayer,density,Strength_plastik,Module_plastik,LSS,Plastik_Tg
0,188,-1.052632,1.758,4.59,253,1.814229,1,-,196.0,319.4,...,23.672,19.0,150.2,v,0.209,1.536,879.0,70.1,77.2,164.0
1,189,-0.526316,1.758,4.48,260,1.723077,1.1,-,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,188,-1.052632,1.759,4.28,257,1.665370,1,-,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_144 = df_144.drop('SA linear', axis=1)
df_145 = df_145.drop('SA linear', axis=1)
df_146 = df_146.drop('SA linear', axis=1)
df_147 = df_147.drop('SA linear', axis=1)
df_151 = df_151.drop('SA linear', axis=1)
df_152 = df_152.drop('SA linear', axis=1)
df_153 = df_153.drop('SA linear', axis=1)
df_154 = df_154.drop('SA linear', axis=1)
df_155 = df_155.drop('SA linear', axis=1)
df_156 = df_156.drop('SA linear', axis=1)
df_157 = df_157.drop('SA linear', axis=1)
df_158 = df_158.drop('SA linear', axis=1)
df_163 = df_163.drop('SA linear', axis=1)
df_164 = df_164.drop('SA linear', axis=1)
df_167 = df_167.drop('SA linear', axis=1)
df_168 = df_168.drop('SA linear', axis=1)
df_169 = df_169.drop('SA linear', axis=1)
df_170 = df_170.drop('SA linear', axis=1)
df_172 = df_172.drop('SA linear', axis=1)
df_173 = df_173.drop('SA linear', axis=1)
df_174 = df_174.drop('SA linear', axis=1)
df_175 = df_175.drop('SA linear', axis=1)
df_177 = df_177.drop('SA linear', axis=1)
df_186 = df_186.drop('SA linear', axis=1)
df_188 = df_188.drop('SA linear', axis=1)
df_197 = df_197.drop('SA linear', axis=1)

In [5]:
df_144 = df_144.replace('-', np.nan)
df_145 = df_145.replace('-', np.nan)
df_146 = df_146.replace('-', np.nan)
df_147 = df_147.replace('-', np.nan)
df_151 = df_151.replace('-', np.nan)
df_152 = df_152.replace('-', np.nan)
df_153 = df_153.replace('-', np.nan)
df_154 = df_154.replace('-', np.nan)
df_155 = df_155.replace('-', np.nan)
df_156 = df_156.replace('-', np.nan)
df_157 = df_157.replace('-', np.nan)
df_158 = df_158.replace('-', np.nan)
df_163 = df_163.replace('-', np.nan)
df_164 = df_164.replace('-', np.nan)
df_167 = df_167.replace('-', np.nan)
df_168 = df_168.replace('-', np.nan)
df_169 = df_169.replace('-', np.nan)
df_170 = df_170.replace('-', np.nan)
df_172 = df_172.replace('-', np.nan)
df_173 = df_173.replace('-', np.nan)
df_174 = df_174.replace('-', np.nan)
df_175 = df_175.replace('-', np.nan)
df_177 = df_177.replace('-', np.nan)
df_186 = df_186.replace('-', np.nan)
df_188 = df_188.replace('-', np.nan)
df_197 = df_197.replace('-', np.nan)

/tmp/ipykernel_11699/3289886207.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_144 = df_144.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_145 = df_145.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_146 = df_146.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_147 = df_147.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_151 = df_151.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_152 = df_152.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_153 = df_153.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_154 = df_154.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_155 = df_155.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_156 = df_156.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_157 = df_157.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_158 = df_158.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_163 = df_163.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_164 = df_164.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:15: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_167 = df_167.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_168 = df_168.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:17: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_169 = df_169.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:18: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_170 = df_170.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:19: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_172 = df_172.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:20: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_173 = df_173.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:21: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_174 = df_174.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:22: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_175 = df_175.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_177 = df_177.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_186 = df_186.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:25: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_188 = df_188.replace('-', np.nan)
/tmp/ipykernel_11699/3289886207.py:26: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_197 = df_197.replace('-', np.nan)

In [6]:
def replace_tech(df):
    if df['technology'][0] == 'v':
        df['technology'] = np.where(df['technology'].isnull(), 'v', 'v')
    else:
        df['technology'] = np.where(df['technology'].isnull(), 'a', 'a')

In [7]:
df_all = [df_144, df_145, df_146, df_147, df_151, df_152, df_153, df_154, df_155, df_156,
      df_157, df_158, df_163, df_164, df_167, df_168, df_169, df_170, df_172, df_173,
      df_174, df_175, df_177, df_186, df_188, df_197]

In [8]:
for df in df_all:
    replace_tech(df)

In [9]:
df_145.head()

,Linera density,Density yarn,Strength Gpa,Module Gpa,lengthening,Mass size,breaking the loop,Surface density of the fabric,Prepreg surface density,Resin content,viscosity,Gelation time,Resin Tg,technology,Thickness of the monolayer,density,Strength_plastik,Module_plastik,LSS,Plastik_Tg
0,188,1.752,4.29,254,1.688976,1.1,26.2,197.5,321.37,38.97,25.2,19.0,152.0,a,0.209,1.555,922.0,71.7,78.9,156.0
1,184,1.751,4.30,255,1.686275,1.2,24.7,NaN,NaN,NaN,NaN,NaN,NaN,a,NaN,NaN,NaN,NaN,NaN,NaN
2,179,1.750,4.62,268,1.723881,1.2,26.3,NaN,NaN,NaN,NaN,NaN,NaN,a,NaN,NaN,NaN,NaN,NaN,NaN
3,189,1.749,4.37,254,1.720472,1.1,25.6,NaN,NaN,NaN,NaN,NaN,NaN,a,NaN,NaN,NaN,NaN,NaN,NaN
4,189,1.749,4.26,255,1.670588,1.0,24.8,NaN,NaN,NaN,NaN,NaN,NaN,a,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
#df_144['technology'] = np.where(df_144['technology'].isnull(), 'v', 'v')
#df_144

In [11]:
def replace_fillna(df):
    
    df['Mass size'] = df['Mass size'].fillna(df['Mass size'].mean())
    df['breaking the loop'] = df['breaking the loop'].fillna(df['breaking the loop'].median())
    df['Surface density of the fabric'] = df['Surface density of the fabric'].fillna(df['Surface density of the fabric'].mean())
    df['Prepreg surface density'] = df['Prepreg surface density'].fillna(df['Prepreg surface density'].mean())
    df['Resin content'] = df['Resin content'].fillna(df['Resin content'].mean())
    df['viscosity'] = df['viscosity'].fillna(df['viscosity'].mean())
    df['Gelation time'] = df['Gelation time'].fillna(df['Gelation time'].mean())
    df['Resin Tg'] = df['Resin Tg'].fillna(df['Resin Tg'].mean())
    df['Thickness of the monolayer'] = df['Thickness of the monolayer'].fillna(df['Thickness of the monolayer'].mean())
    df['density'] = df['density'].fillna(df['density'].mean())
    df['Strength_plastik'] = df['Strength_plastik'].fillna(df['Strength_plastik'].median())
    df['Module_plastik '] = df['Module_plastik '].fillna(df['Module_plastik '].median())
    df['LSS'] = df['LSS'].fillna(df['LSS'].mean())
    df['Plastik_Tg'] = df['Plastik_Tg'].fillna(df['Plastik_Tg'].mean())
    
    return df

In [12]:
for df in df_all:
    replace_fillna(df)

In [13]:
df_144.head()

,Linera density,Density yarn,Strength Gpa,Module Gpa,lengthening,Mass size,breaking the loop,Surface density of the fabric,Prepreg surface density,Resin content,viscosity,Gelation time,Resin Tg,technology,Thickness of the monolayer,density,Strength_plastik,Module_plastik,LSS,Plastik_Tg
0,188,1.758,4.59,253,1.814229,1.0,24.3,196.0,319.4,38.63,23.672,19.0,150.2,v,0.209,1.536,879.0,70.1,77.2,164.0
1,189,1.758,4.48,260,1.723077,1.1,24.3,196.0,319.4,38.63,23.672,19.0,150.2,v,0.209,1.536,879.0,70.1,77.2,164.0
2,188,1.759,4.28,257,1.665370,1.0,24.3,196.0,319.4,38.63,23.672,19.0,150.2,v,0.209,1.536,879.0,70.1,77.2,164.0
3,187,1.758,4.77,256,1.863281,1.0,24.3,196.0,319.4,38.63,23.672,19.0,150.2,v,0.209,1.536,879.0,70.1,77.2,164.0
4,190,1.757,4.56,255,1.788235,0.9,24.3,196.0,319.4,38.63,23.672,19.0,150.2,v,0.209,1.536,879.0,70.1,77.2,164.0

In [14]:
df_151.head()

,Linera density,Density yarn,Strength Gpa,Module Gpa,lengthening,Mass size,breaking the loop,Surface density of the fabric,Prepreg surface density,Resin content,viscosity,Gelation time,Resin Tg,technology,Thickness of the monolayer,density,Strength_plastik,Module_plastik,LSS,Plastik_Tg
0,188,1.760,4.65,263,1.768061,0.9,25.5,198.0,318.17,37.77,23.97,15.0,150.0,a,0.201,1.529,928.0,68.9,73.9,155.0
1,186,1.755,4.57,257,1.778210,1.0,25.5,198.0,318.17,37.77,23.97,15.0,150.0,a,0.201,1.529,928.0,68.9,73.9,155.0
2,185,1.754,4.37,257,1.700389,1.0,25.5,198.0,318.17,37.77,23.97,15.0,150.0,a,0.201,1.529,928.0,68.9,73.9,155.0
3,186,1.758,4.51,246,1.833333,0.8,25.5,198.0,318.17,37.77,23.97,15.0,150.0,a,0.201,1.529,928.0,68.9,73.9,155.0
4,187,1.755,4.27,255,1.674510,0.9,25.5,198.0,318.17,37.77,23.97,15.0,150.0,a,0.201,1.529,928.0,68.9,73.9,155.0

In [15]:
df_all_concat = pd.concat([df_144, df_145, df_146, df_147, df_151, df_152, df_153, df_154, df_155, df_156,
      df_157, df_158, df_163, df_164, df_167, df_168, df_169, df_170, df_172, df_173,
      df_174, df_175, df_177, df_186, df_188, df_197])

df_all_concat

,Linera density,Density yarn,Strength Gpa,Module Gpa,lengthening,Mass size,breaking the loop,Surface density of the fabric,Prepreg surface density,Resin content,viscosity,Gelation time,Resin Tg,technology,Thickness of the monolayer,density,Strength_plastik,Module_plastik,LSS,Plastik_Tg
0,188.0,1.758,4.590,253.0,1.814229,1.000000,24.3,196.0,319.4,38.63,23.672,19.00,150.20,v,0.2090,1.5360,879.0,70.1,77.20,164.0
1,189.0,1.758,4.480,260.0,1.723077,1.100000,24.3,196.0,319.4,38.63,23.672,19.00,150.20,v,0.2090,1.5360,879.0,70.1,77.20,164.0
2,188.0,1.759,4.280,257.0,1.665370,1.000000,24.3,196.0,319.4,38.63,23.672,19.00,150.20,v,0.2090,1.5360,879.0,70.1,77.20,164.0
3,187.0,1.758,4.770,256.0,1.863281,1.000000,24.3,196.0,319.4,38.63,23.672,19.00,150.20,v,0.2090,1.5360,879.0,70.1,77.20,164.0
4,190.0,1.757,4.560,255.0,1.788235,0.900000,24.3,196.0,319.4,38.63,23.672,19.00,150.20,v,0.2090,1.5360,879.0,70.1,77.20,164.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408,189.0,1.783,4.640,271.0,1.712177,1.283333,23.5,206.0,335.9,38.30,23.420,16.78,150.44,v,0.2235,1.5215,899.0,71.0,86.45,163.0
409,189.0,1.780,4.500,284.0,1.584507,1.283333,23.5,206.0,335.9,38.30,23.420,16.78,150.44,v,0.2235,1.5215,899.0,71.0,86.45,163.0
410,190.0,1.783,4.838,270.0,1.791852,1.283333,23.5,206.0,335.9,38.30,23.420,16.78,150.44,v,0.2235,1.5215,899.0,71.0,86.45,163.0
411,191.0,1.779,4.820,271.0,1.778598,1.283333,23.5,206.0,335.9,38.30,23.420,16.78,150.44,v,0.2235,1.5215,899.0,71.0,86.45,163.0
412,189.0,1.782,4.630,270.0,1.714815,1.283333,23.5,206.0,335.9,38.30,23.420,16.78,150.44,v,0.2235,1.5215,899.0,71.0,86.45,163.0

In [16]:
df_all_concat.to_csv('data/dataset.csv', index=False, encoding='utf-8')

In [17]:
df_all_concat_2 = pd.read_csv('data/dataset.csv')

df_all_concat_2

,Linera density,Density yarn,Strength Gpa,Module Gpa,lengthening,Mass size,breaking the loop,Surface density of the fabric,Prepreg surface density,Resin content,viscosity,Gelation time,Resin Tg,technology,Thickness of the monolayer,density,Strength_plastik,Module_plastik,LSS,Plastik_Tg
0,188.0,1.758,4.590,253.0,1.814229,1.000000,24.3,196.0,319.4,38.63,23.672,19.00,150.20,v,0.2090,1.5360,879.0,70.1,77.20,164.0
1,189.0,1.758,4.480,260.0,1.723077,1.100000,24.3,196.0,319.4,38.63,23.672,19.00,150.20,v,0.2090,1.5360,879.0,70.1,77.20,164.0
2,188.0,1.759,4.280,257.0,1.665370,1.000000,24.3,196.0,319.4,38.63,23.672,19.00,150.20,v,0.2090,1.5360,879.0,70.1,77.20,164.0
3,187.0,1.758,4.770,256.0,1.863281,1.000000,24.3,196.0,319.4,38.63,23.672,19.00,150.20,v,0.2090,1.5360,879.0,70.1,77.20,164.0
4,190.0,1.757,4.560,255.0,1.788235,0.900000,24.3,196.0,319.4,38.63,23.672,19.00,150.20,v,0.2090,1.5360,879.0,70.1,77.20,164.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11123,189.0,1.783,4.640,271.0,1.712177,1.283333,23.5,206.0,335.9,38.30,23.420,16.78,150.44,v,0.2235,1.5215,899.0,71.0,86.45,163.0
11124,189.0,1.780,4.500,284.0,1.584507,1.283333,23.5,206.0,335.9,38.30,23.420,16.78,150.44,v,0.2235,1.5215,899.0,71.0,86.45,163.0
11125,190.0,1.783,4.838,270.0,1.791852,1.283333,23.5,206.0,335.9,38.30,23.420,16.78,150.44,v,0.2235,1.5215,899.0,71.0,86.45,163.0
11126,191.0,1.779,4.820,271.0,1.778598,1.283333,23.5,206.0,335.9,38.30,23.420,16.78,150.44,v,0.2235,1.5215,899.0,71.0,86.45,163.0
11127,189.0,1.782,4.630,270.0,1.714815,1.283333,23.5,206.0,335.9,38.30,23.420,16.78,150.44,v,0.2235,1.5215,899.0,71.0,86.45,163.0